# text_cleaning package — public compatibility layer.

from .dictionary import (
    _strip_vietnamese_accents,
    _normalize_vietnamese_place_phrases,
    _normalize_ocr_spelling_by_dictionary,
    _is_known_token,
)
from .spelling import (
    _choose_better_duplicate_token,
    _remove_adjacent_duplicate_ocr_tokens,
    _fix_latin_brand_ocr_artifacts,
    _clean_spelling,
    _has_vietnamese_mark,
    _merge_primary_diacritics,
    _vietnamese_tone_preference,
    _has_vietnamese_shaped_vowel,
    _merge_best_diacritics,
)
from .junk import (
    _is_junk_line,
    _clean_junk_words,
    _looks_like_junk_token,
    _drop_stray_leading_edge_token,
    _is_category_or_description_segment,
)
from .final_cleanup import _clean_final_ocr_text
from .rescue import (
    _continuation_tokens_are_valid,
    _append_missing_known_suffix,
    _merge_overlapping_ocr_continuation,
)
from .quality import (
    _junk_token_count,
    _looks_like_bad_ocr,
    _looks_like_vietnamese_gibberish,
    _score_ocr_text_quality,
    _ocr_artifact_score,
    _normalized_regresses_quality,
    _ocr_tokens,
    _contains_token_subsequence,
    _is_clean_short_brand_candidate,
    _texts_are_unrelated,
    _normalized_has_valid_main_name_extension,
    _normalized_adds_suspicious_text,
    _segment_has_strong_signal,
    _is_weak_edge_segment,
    _clean_ocr_edge_segments,
)

__all__ = [
    _strip_vietnamese_accents,
    _normalize_vietnamese_place_phrases,
    _normalize_ocr_spelling_by_dictionary,
    _is_known_token,
    _choose_better_duplicate_token,
    _remove_adjacent_duplicate_ocr_tokens,
    _fix_latin_brand_ocr_artifacts,
    _clean_spelling,
    _has_vietnamese_mark,
    _merge_primary_diacritics,
    _vietnamese_tone_preference,
    _has_vietnamese_shaped_vowel,
    _merge_best_diacritics,
    _is_junk_line,
    _clean_junk_words,
    _looks_like_junk_token,
    _drop_stray_leading_edge_token,
    _is_category_or_description_segment,
    _clean_final_ocr_text,
    _continuation_tokens_are_valid,
    _append_missing_known_suffix,
    _merge_overlapping_ocr_continuation,
    _junk_token_count,
    _junk_token_count,
    _looks_like_bad_ocr,
    _looks_like_vietnamese_gibberish,
    _score_ocr_text_quality,
    _ocr_artifact_score,
    _normalized_regresses_quality,
    _ocr_tokens,
    _contains_token_subsequence,
    _is_clean_short_brand_candidate,
    _texts_are_unrelated,
    _normalized_has_valid_main_name_extension,
    _normalized_adds_suspicious_text,
    _segment_has_strong_signal,
    _is_weak_edge_segment,
    _clean_ocr_edge_segments,
]
